name: Auto-approve PRs by repository owner

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'bsteinbock'
    steps:
      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
